Fail CI

diff --git a/.github/workflows/check_secret.yml b/.github/workflows/check_secret.yml
--- a/.github/workflows/check_secret.yml
+++ b/.github/workflows/check_secret.yml
@@ -44,3 +44,5 @@ jobs:
         run: |
           echo "Checked out SHA: $(git rev-parse HEAD)"
           echo "Expected SHA: ${{ github.event.pull_request.head.sha }}"
+          echo "Fail"
+          exit 1
